### ISSUE TITLE
Telemetry service and Prometheus optimizations

### ISSUE THREAD

**Issue by siggy** [runconduit/conduit#299]
Followup from #260, there are a number of additional optimizations we can make to optimize our telemetry system. Specifically, in Telemetry Service, and in our usage of Prometheus.

This list is in descending order of readiness / feasibility:

- [x] #298 Don't query for entire timeseries on summary queries, instead move requests off of Prometheus' `queryRange` endpoint, onto `query`.
- [x]  #298 Decrease `defaultVectorRange` (and use it all the time) from `1m` to `30s`, 3x multiple of Prometheus' `scrape_interval: 10s`.
- [x] #344 Investigate upgrading to Prometheus 2.0+.
- [x] #323 In public-api / `grpc-server.go`, certain queries yield 5 requests to Prometheus, make these parallel. For example: `api/metrics?&timeseries=true&target_deploy=emojivoto/voting&window=10m`.
- [x] #336 Investigate adding write-side Prometheus recording rules for `histogram_quantile` and latency calculations.
- [x] #328 Investigate `/api/metrics` failing with large pod count
- [ ] Investigate query optimizations in the conduit dashboard. Consider modifying the public API to allow fewer and/or faster queries.
- [ ] Investigate increasing the value of `step`, tradeoff is less resolution.
- [ ] Investigate connecting `public-api` directly to Prometheus, removing `telemetry` from the query path. A drawback to this approach is the `telemetry` service would no longer be the single endpoint into Prometheus.

**Comment by wmorgan** [comment]
Is all of this planned for 0.3 or should we remove this tracking ticket and assign individual ones?

**Comment by siggy** [comment]
@wmorgan The scoped sub-tasks are planned for 0.3, and associated with that milestone. The scope of this tracking ticket probably goes beyond 0.3, I've removed it from the milestone.

**Comment by siggy** [comment]
Continuing work on Telemetry is tracked via https://github.com/runconduit/conduit/projects/2, closing this issue.
